#!/usr/bin/env python

"""
Test VREF gitolite hook script
"""

import sys
from datetime import datetime

# Print out command line arguments
with open('test.log', "a") as log:
    script = sys.argv.pop(0)
    log.write("%s : %s : arguments : %s\n" % (datetime.now(), script, ", ".join(sys.argv)))


# Print out command line arguments
import os
with open(os.path.dirname(os.path.realpath(__file__))+'/test.log', "a") as log:
    script = sys.argv.pop(0)
    log.write("%s : %s : arguments : %s\n" % (datetime.now(), script, ", ".join(sys.argv)))
