#!/usr/bin/env python

"""
Update VREF gitolite hook script
takes new commits and places them in database
"""

from __future__ import print_function
import os
import sys
dir = os.path.dirname(os.path.realpath(__file__))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "joltem.settings")

python_paths = os.environ['PYTHONPATH'].split(os.pathsep)

from datetime import datetime
from joltem.models import User
from git.models import Repository
from solution.models import Solution

# Print out command line arguments
with open(dir+'/test.log', "a") as log_file:
    log = lambda line: log_file.write("%s\n" % line)
    args = sys.argv
    script = args.pop(0)
    # Get VREF passed arguments
    reference = args[0]
    old_sha = args[1]
    new_sha = args[2]
    mode = args[5]
    username = args[7]
    repository_id = args[8]
    user = User.objects.get(username=username)
    repository = Repository.objects.get(id=repository_id)
    log("%s : %s to %s on %s by %s : %s..%s " % (datetime.now(), mode, reference, repository.full_name, user.first_name, old_sha, new_sha))
    if mode == 'W':
        split_reference = reference.split('/')
        if split_reference[0] == 'refs' \
            and split_reference[1] == 'heads' \
                and split_reference[2] == 's':
            solution_id = split_reference[3]
            solution = Solution.objects.get(id=solution_id)
            log("Solution : %s by %s" % (solution.task.title, solution.user.first_name))
            decline = lambda reason: print("VREF/UPDATE/%s/%d %s" % (user.username, repository.id, reason))
            if not solution.is_accepted:
                decline("Solution is not accepted yet, you can start working on a personal branch if you wish.")
                log("Denied.")
            elif solution.user_id != user.id:
                decline("Only the solution owner can push to this branch, file a pull request from a personal branch if you wish.")
                log("Denied.")
            else:
                log("Accepted")

    # TODO allow project administrators to push to master
    # TODO deny access to personal branches



