import os
from git.models import Repository

# Configurations for the gitolite admin repo

prefix = """
#===========================
# Administration
#===========================

repo\tgitolite-admin
\tRW\t=\temil

#===========================
# Repositories
#===========================

"""

def update_permissions():
    """
    Update gitolite permissions
    """
    # Find file paths
    gitolite_admin_directory = os.path.dirname(os.path.realpath(__file__))+"/gitolite-admin/"
    gitolite_conf_file_path = gitolite_admin_directory+"conf/gitolite.conf"
    with open(gitolite_conf_file_path, 'w') as f:
        f.write("#***************************\n")
        f.write("# Generated by Joltem\n")
        f.write("#***************************\n")
        f.write(prefix)
        repos = Repository.objects.all()
        for repo in repos:
            # Repository permissions
            f.write("repo\t%s\n" % repo.path)
            # Branch permissions
            branches = repo.branch_set.filter()
            for branch in branches:
                assignees = branch.task_branch.assignees.all()
                f.write("\t%s\t^refs/heads/task/%d/%d$\t=\t%s\n" % (
                    'RW',
                    branch.task_branch.task_id,
                    branch.task_branch_id,
                    "\t".join(assignee.username for assignee in assignees)
                ))

    print "\n*** Wrote configuration file to %s, is closed : %s.\n" % (gitolite_conf_file_path, f.closed)
    # Commit and push changes
    from subprocess import call
    print "\n*** Commit permission changes\n."
    call("git --git-dir=%s.git --work-tree=%s commit -v -am 'Permission changes.'" % (gitolite_admin_directory, gitolite_admin_directory), shell=True)
    print "\n*** Push permission changes.\n"
    call("git --git-dir=%s.git --work-tree=%s push -v" % (gitolite_admin_directory, gitolite_admin_directory), shell=True)
