import os
from git.models import Repository

# Configurations for the gitolite admin repo
gitolite_admin_conf = """
repo gitolite-admin
    RW = emil
"""


def update_permissions():
    """
    Update gitolite permissions
    """
    # Find file paths
    gitolite_admin_directory = os.path.dirname(os.path.realpath(__file__))+"/gitolite-admin/"
    gitolite_conf_file_path = gitolite_admin_directory+"conf/gitolite.conf"
    with open(gitolite_conf_file_path, 'w') as f:
        f.write("#***************************\n")
        f.write("# Generated by Joltem\n")
        f.write("#***************************\n")
        f.write(gitolite_admin_conf)
        repos = Repository.objects.all()
        for repo in repos:
            # Repository permissions
            f.write("repo\t%s\n" % repo.path)
            # Branch permissions
            branches = repo.branch_set.filter()
            for branch in branches:
                assignees = branch.task_branch.assignees.all()
                for assignee in assignees:
                    f.write("\t%s\t^refs/heads/task/%d/%d$\t=\t%s\n" % ('RW', branch.task_branch.task_id, branch.task_branch_id, assignee.username))

    print "\n*** Wrote configuration file to %s, is closed : %s.\n" % (gitolite_conf_file_path, f.closed)
    # Output config file to STDOUT
    from subprocess import call
    call("cat %s" % gitolite_conf_file_path, shell=True)
    print "\n*** Commit permission changes\n."
    call("git --git-dir=%s.git --work-tree=%s commit -v -am 'Permission changes.'" % (gitolite_admin_directory, gitolite_admin_directory), shell=True)
    print "\n*** Push permission changes.\n"
    call("git --git-dir=%s.git --work-tree=%s push -v" % (gitolite_admin_directory, gitolite_admin_directory), shell=True)
