# -*- mode: ruby -*-

Vagrant.configure('2') do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--memory', 1024]
  end

  config.vm.hostname = 'joltem.local'

  config.vm.network :private_network, ip: '33.33.33.33'

  config.vm.synced_folder '..', '/joltem/'
end
